"""add note column in certificate table

Revision ID: 14775eb2f3b4
Revises: 84fc7bc201e6
Create Date: 2017-10-19 03:27:14.168619

"""

# revision identifiers, used by Alembic.
revision = '14775eb2f3b4'
down_revision = '84fc7bc201e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate', 'note')
    # ### end Alembic commands ###
