"""add Vietnam Geo DB

Revision ID: 32c1cbb13ec2
Revises: b91f6260d520
Create Date: 2017-07-19 11:31:03.582990

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32c1cbb13ec2'
down_revision = 'b91f6260d520'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
                    sa.Column('province_id', sa.String(length=64),
                              nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('province_id'),
                    mysql_default_charset='utf8'
                    )
    op.create_index(op.f('ix_province_name'), 'province', ['name'],
                    unique=False)
    op.create_table('district',
                    sa.Column('district_id', sa.String(length=64),
                              nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=30), nullable=False),
                    sa.Column('location', sa.String(length=30), nullable=False),
                    sa.Column('province_id', sa.String(length=64),
                              nullable=False),
                    sa.ForeignKeyConstraint(['province_id'],
                                            ['province.province_id'], ),
                    sa.PrimaryKeyConstraint('district_id'),
                    mysql_default_charset='utf8'
                    )
    op.create_index(op.f('ix_district_name'), 'district', ['name'],
                    unique=False)
    op.create_index(op.f('ix_district_province_id'), 'district',
                    ['province_id'], unique=False)
    op.create_table('ward',
                    sa.Column('ward_id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=100), nullable=False),
                    sa.Column('location', sa.String(length=100),
                              nullable=False),
                    sa.Column('district_id', sa.String(length=100),
                              nullable=False),
                    sa.ForeignKeyConstraint(['district_id'],
                                            ['district.district_id'], ),
                    sa.PrimaryKeyConstraint('ward_id'),
                    mysql_default_charset='utf8'
                    )
    op.create_index(op.f('ix_ward_district_id'), 'ward', ['district_id'],
                    unique=False)
    op.create_index(op.f('ix_ward_name'), 'ward', ['name'], unique=False)
    op.add_column('associate_group',
                  sa.Column('province_id', sa.String(length=64), nullable=True))
    op.drop_constraint('associate_group_ibfk_1', 'associate_group',
                       type_='foreignkey')
    op.create_foreign_key(None, 'associate_group', 'province', ['province_id'],
                          ['province_id'])
    op.drop_column('associate_group', 'region_id')
    op.add_column('group',
                  sa.Column('district_id', sa.String(length=64), nullable=True))
    op.add_column('group',
                  sa.Column('province_id', sa.String(length=64), nullable=True))
    op.add_column('group',
                  sa.Column('ward_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_group_district_id'), 'group', ['district_id'],
                    unique=False)
    op.create_index(op.f('ix_group_province_id'), 'group', ['province_id'],
                    unique=False)
    op.create_index(op.f('ix_group_ward_id'), 'group', ['ward_id'],
                    unique=False)
    op.drop_constraint('group_ibfk_2', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'district', ['district_id'],
                          ['district_id'])
    op.create_foreign_key(None, 'group', 'province', ['province_id'],
                          ['province_id'])
    op.create_foreign_key(None, 'group', 'ward', ['ward_id'], ['ward_id'])
    op.drop_column('group', 'province')
    op.drop_column('group', 'region_id')
    op.drop_column('group', 'ward')
    op.drop_column('group', 'district')
    op.add_column('user',
                  sa.Column('province_id', sa.String(length=64), nullable=True))
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'province', ['province_id'],
                          ['province_id'])
    op.drop_column('user', 'region_id')
    op.drop_table('region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('region_id', mysql.VARCHAR(length=64),
                                    nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'region', ['region_id'],
                          ['id'])
    op.drop_column('user', 'province_id')
    op.add_column('group', sa.Column('district', mysql.VARCHAR(length=255),
                                     nullable=True))
    op.add_column('group',
                  sa.Column('ward', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('group', sa.Column('region_id', mysql.VARCHAR(length=64),
                                     nullable=True))
    op.add_column('group', sa.Column('province', mysql.VARCHAR(length=255),
                                     nullable=True))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_ibfk_2', 'group', 'region', ['region_id'],
                          ['id'])
    op.drop_index(op.f('ix_group_ward_id'), table_name='group')
    op.drop_index(op.f('ix_group_province_id'), table_name='group')
    op.drop_index(op.f('ix_group_district_id'), table_name='group')
    op.drop_column('group', 'ward_id')
    op.drop_column('group', 'province_id')
    op.drop_column('group', 'district_id')
    op.add_column('associate_group',
                  sa.Column('region_id', mysql.VARCHAR(length=64),
                            nullable=True))
    op.drop_constraint(None, 'associate_group', type_='foreignkey')
    op.create_foreign_key('associate_group_ibfk_1', 'associate_group', 'region',
                          ['region_id'], ['id'])
    op.drop_column('associate_group', 'province_id')
    op.create_table('region',
                    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
                    sa.Column('region_code', mysql.VARCHAR(length=64),
                              nullable=True),
                    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
                    sa.Column('description', mysql.VARCHAR(length=255),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='utf8',
                    mysql_engine='InnoDB'
                    )
    op.drop_index(op.f('ix_ward_name'), table_name='ward')
    op.drop_index(op.f('ix_ward_district_id'), table_name='ward')
    op.drop_table('ward')
    op.drop_index(op.f('ix_district_province_id'), table_name='district')
    op.drop_index(op.f('ix_district_name'), table_name='district')
    op.drop_table('district')
    op.drop_index(op.f('ix_province_name'), table_name='province')
    op.drop_table('province')
    # ### end Alembic commands ###
