"""trackable user info

Revision ID: 56502d362ab5
Revises: 456a945560f6
Create Date: 2017-07-05 15:05:42.204968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = '56502d362ab5'
down_revision = '456a945560f6'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=50),
                                    nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=50),
                                    nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(),
                                    nullable=True))
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(),
                                    nullable=True,
                                    default=func.utc_timestamp()))
    op.add_column('user', sa.Column('login_count', sa.Integer(),
                                    nullable=True))

    op.create_table('roles_users',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'current_login_at')
    op.drop_column('user', 'login_count')
    op.drop_table('roles_users')
    # ### end Alembic commands ###
