"""make deleted_at and modify_info column to private property

Revision ID: 5c3ebec69cdd
Revises: ef552a46d4ff
Create Date: 2017-07-26 21:28:30.229291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c3ebec69cdd'
down_revision = 'ef552a46d4ff'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associate_group',
                  sa.Column('_deleted_at', sa.DateTime(), nullable=True))
    op.add_column('associate_group',
                  sa.Column('_modify_info', sa.String(length=255),
                            nullable=True))
    op.drop_index('a_group_code_index', table_name='associate_group')
    op.create_index('a_group_code_index', 'associate_group',
                    ['associate_group_code', '_deleted_at'], unique=False)
    op.drop_column('associate_group', 'modify_info')
    op.drop_column('associate_group', 'deleted_at')
    op.add_column('certificate',
                  sa.Column('_deleted_at', sa.DateTime(), nullable=True))
    op.add_column('certificate',
                  sa.Column('_modify_info', sa.String(length=255),
                            nullable=True))
    op.drop_index('certificate_code_index', table_name='certificate')
    op.create_index('certificate_code_index', 'certificate',
                    ['certificate_code', '_deleted_at'], unique=False)
    op.drop_index('certificate_code_index2', table_name='certificate')
    op.drop_column('certificate', 'modify_info')
    op.drop_column('certificate', 'deleted_at')
    op.add_column('farmer',
                  sa.Column('_deleted_at', sa.DateTime(), nullable=True))
    op.add_column('farmer', sa.Column('_modify_info', sa.String(length=255),
                                      nullable=True))
    op.drop_index('farmer_code_index', table_name='farmer')
    op.create_index('farmer_code_index', 'farmer',
                    ['farmer_code', '_deleted_at'], unique=False)
    op.drop_column('farmer', 'modify_info')
    op.drop_column('farmer', 'deleted_at')
    op.add_column('group',
                  sa.Column('_deleted_at', sa.DateTime(), nullable=True))
    op.add_column('group', sa.Column('_modify_info', sa.String(length=255),
                                     nullable=True))
    op.drop_index('group_code_index', table_name='group')
    op.create_index('group_code_index', 'group', ['group_code', '_deleted_at'],
                    unique=False)
    op.drop_column('group', 'modify_info')
    op.drop_column('group', 'deleted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group',
                  sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.add_column('group', sa.Column('modify_info', mysql.VARCHAR(length=255),
                                     nullable=True))
    op.drop_index('group_code_index', table_name='group')
    op.create_index('group_code_index', 'group', ['group_code', 'deleted_at'],
                    unique=False)
    op.drop_column('group', '_modify_info')
    op.drop_column('group', '_deleted_at')
    op.add_column('farmer',
                  sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.add_column('farmer', sa.Column('modify_info', mysql.VARCHAR(length=255),
                                      nullable=True))
    op.drop_index('farmer_code_index', table_name='farmer')
    op.create_index('farmer_code_index', 'farmer',
                    ['farmer_code', 'deleted_at'], unique=False)
    op.drop_column('farmer', '_modify_info')
    op.drop_column('farmer', '_deleted_at')
    op.add_column('certificate',
                  sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.add_column('certificate',
                  sa.Column('modify_info', mysql.VARCHAR(length=255),
                            nullable=True))
    op.create_index('certificate_code_index2', 'certificate',
                    ['certificate_code'], unique=False)
    op.drop_index('certificate_code_index', table_name='certificate')
    op.create_index('certificate_code_index', 'certificate',
                    ['certificate_code', 'deleted_at'], unique=False)
    op.drop_column('certificate', '_modify_info')
    op.drop_column('certificate', '_deleted_at')
    op.add_column('associate_group',
                  sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.add_column('associate_group',
                  sa.Column('modify_info', mysql.VARCHAR(length=255),
                            nullable=True))
    op.drop_index('a_group_code_index', table_name='associate_group')
    op.create_index('a_group_code_index', 'associate_group',
                    ['associate_group_code', 'deleted_at'], unique=False)
    op.drop_column('associate_group', '_modify_info')
    op.drop_column('associate_group', '_deleted_at')
    # ### end Alembic commands ###
