"""empty message

Revision ID: 84fc7bc201e6
Revises: 2159f60b94ab
Create Date: 2017-08-20 12:42:40.461404

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '84fc7bc201e6'
down_revision = '2159f60b94ab'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('district_index', 'district', ['name'], unique=False)
    op.create_index('province_index', 'province', ['name'], unique=False)
    op.drop_index('ix_user_fullname', table_name='user')
    op.create_index(op.f('ix_user_fullname'), 'user',
                    ['fullname'], unique=True)
    op.create_index('ward_index', 'ward', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ward_index', table_name='ward')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.create_index('ix_user_fullname', 'user', ['fullname'], unique=False)
    op.drop_index('province_index', table_name='province')
    op.drop_index('district_index', table_name='district')
    # ### end Alembic commands ###
