"""empty message

Revision ID: b91f6260d520
Revises: 56502d362ab5
Create Date: 2017-07-16 18:17:32.791453

"""

# revision identifiers, used by Alembic.
revision = 'b91f6260d520'
down_revision = '56502d362ab5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('associate_group',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('region_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('modify_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('associate_group_id', sa.String(length=64), nullable=True),
    sa.Column('region_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('modify_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['associate_group_id'], ['associate_group.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_group_id', sa.String(length=64), nullable=True),
    sa.Column('group_area', sa.String(length=64), nullable=True),
    sa.Column('certificate_start_date', sa.DateTime(), nullable=True),
    sa.Column('gov_certificate_id', sa.String(length=64), nullable=True),
    sa.Column('certificate_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('valid', 'invalid', 'checking', name='certificatestatetype'), nullable=True),
    sa.Column('re_verify_state', sa.Enum('not_check', 'ok', 'warning', name='certificatereverifystatetype'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('modify_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner_group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gendertype'), nullable=True),
    sa.Column('type', sa.Enum('member', 'reviewer', name='farmertype'), nullable=True),
    sa.Column('group_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('modify_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('region_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=True)
    op.drop_index('ix_users_email', table_name='user')
    op.create_foreign_key(None, 'user', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_users_email', 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'region_id')
    op.drop_table('farmer')
    op.drop_table('certificate')
    op.drop_table('group')
    op.drop_table('associate_group')
    op.drop_table('region')
    # ### end Alembic commands ###
