"""add column created_at for farmer, group, agroup

Revision ID: c7b7fb8e6536
Revises: 91b7a3d00a9e
Create Date: 2018-04-12 01:18:01.226407

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c7b7fb8e6536'
down_revision = '91b7a3d00a9e'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associate_group', sa.Column('created_at', sa.Integer(),
                                               nullable=True))
    op.add_column('farmer', sa.Column('created_at', sa.Integer(),
                                      nullable=True))
    op.add_column('group', sa.Column('created_at', sa.Integer(),
                                     nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'created_at')
    op.drop_column('farmer', 'created_at')
    op.drop_column('associate_group', 'created_at')
    # ### end Alembic commands ###
